const ADD_COINS = "ADD_COINS";
const SHOW_MODAL = "SHOW_MODAL";
const HIDE_MODAL = "HIDE_MODAL";
const BUY_PRODUCT = "BUY_PRODUCT";
const SELL_PRODUCT = "SELL_PRODUCT";
const ADD_ITEM_TO_PROD = "ADD_ITEM_TO_PROD";
const REMOVE_ITEM_FROM_PROD = "REMOVE_ITEM_FROM_PROD";
const SET_ROBOT_DONE = "SET_ROBOT_DONE";

const MUTATIONS_TYPES = {
    ADD_COINS,
    SHOW_MODAL,
    HIDE_MODAL,
    BUY_PRODUCT,
    SELL_PRODUCT,
    ADD_ITEM_TO_PROD,
    REMOVE_ITEM_FROM_PROD,
    SET_ROBOT_DONE
}

export default MUTATIONS_TYPES;