const ADD_COINS = "ADD_COINS";
const SHOW_MODAL = "SHOW_MODAL";
const HIDE_MODAL = "HIDE_MODAL";
const BUY_PRODUCT = "BUY_PRODUCT";
const SELL_PRODUCT = "SELL_PRODUCT";

const MUTATIONS_TYPES = {
    ADD_COINS,
    SHOW_MODAL,
    HIDE_MODAL,
    BUY_PRODUCT,
    SELL_PRODUCT
}

export default MUTATIONS_TYPES;